[package]
name = "day01"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part2"
path = "src/main.rs"

[[bin]]
name = "playground"
path = "src/play.rs"

[dependencies]
anyhow = "1"
itertools = "0.10"
