CXXFLAGS=-Wall -Wextra --std=c++20 -O3 -march=native -g -I/home/pseyfert/coding/explore-rangev3/install-range-v3/include
LDLIBS=-L/home/pseyfert/coding/explore-rangev3/install-range-v3/lib

all: main
