CPPFLAGS=-I/home/pseyfert/coding/explore-SOAContainer/install/include -I/home/pseyfert/coding/explore-rangev3/install-range-v3/include

CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2022/compilers/bin/nvc++
CXXFLAGS=-gpu=ccnative --c++20 -acc=gpu -stdpar=gpu -Minfo=stdpar

# CXXFLAGS=-Wall -Wextra --std=c++20 -O3 -march=native -g -I/home/pseyfert/coding/explore-rangev3/install-range-v3/include
# LDLIBS=-L/home/pseyfert/coding/explore-rangev3/install-range-v3/lib -ltbb
